"""AHE arm of the head-to-head: run AHE's evolve.py on the shared task pool.

This runs AHE *as designed* (its evaluate->analyze->improve loop, gpt-5.4 actor
at effort=high, evolve agent at effort=xhigh) on the SAME optimization pool
harness_studio uses, then extracts AHE's best evolved harness so it can be scored
on the SAME locked held-out pile.

Subcommands
-----------
    prepare      build the 10-task dataset dir + the AHE config overlay; print
                 the exact `uv run python evolve.py` command (no spend).
    extract-best <exp_dir> <out_dir>
                 copy AHE's workspace and checkout its best iteration (per
                 best_ever.json) so tb2_score.py can score it on the held-out pile.

Fairness notes (documented in the final report):
* Agent Debugger is OFF (the only locally-validated AHE path; inherits the
  -wo-adb overlay). This slightly handicaps AHE's analysis layer.
* explore_agent is OFF (needs a SERPER key we don't have; it would also give AHE
  a web-research advantage our Strategist lacks). Both omissions are disclosed.
* The actor model (gpt-5.4) is identical to our arm; only the optimizer differs.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from examples.tb2_config import opt_tasks  # noqa: E402
from studio.benchmark.nexau import DEFAULT_AHE_DIR, DEFAULT_TASK_CACHE  # noqa: E402

AHE = DEFAULT_AHE_DIR
OVERLAY_PATH = AHE / "configs" / "experiments" / "exp-tb2-h2h.yaml"
DATASET_DIR = AHE / ".tb2_h2h_dataset"  # gitignored scratch; 10 symlinked tasks


def _task_dir(task_id: str) -> Path:
    matches = sorted(DEFAULT_TASK_CACHE.glob(f"*/{task_id}"))
    matches = [m for m in matches if m.is_dir()]
    if not matches:
        raise FileNotFoundError(f"task {task_id!r} not in {DEFAULT_TASK_CACHE}")
    return matches[0]


def build_dataset(dest: Path) -> list[str]:
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    tasks = opt_tasks()
    for t in tasks:
        (dest / t).symlink_to(_task_dir(t), target_is_directory=True)
    return tasks


def write_overlay(dataset_dir: Path, iterations: int, n_concurrent: int,
                  timeout_multiplier: float) -> Path:
    overlay = f"""# AUTO-GENERATED by examples/tb2_ahe_arm.py — head-to-head vs harness_studio.
# Inherits the proven full-effort gpt-5.4 (no-ADB) overlay; runs locally on Docker
# over the SHARED optimization pool (the 10 non-held-out tasks).
_base: "./exp-simple-code-gpt54-wo-adb.yaml"
_name: "tb2-h2h"
_description: "AHE arm of the harness_studio head-to-head (same input harness, same actor, shared task pool)."
_tags: ["headtohead", "tb2", "docker", "local"]

# Shared optimization pool (10 tasks); `path` takes precedence over `dataset`.
path: "{dataset_dir}"

max_iterations: {iterations}
target_pass_rate: 0.99   # never early-stop; run all {iterations} iterations

harbor:
  env: docker
  k: 1
  n_concurrent: {n_concurrent}
  force_build: false
  timeout_multiplier: {timeout_multiplier}

# Evolve agent at full-effort "high" (the flagship code-agent effort). The
# inherited "xhigh" is locally-unvalidated and far slower; "high" keeps the run
# completing overnight while still giving AHE a strong proposer. (Disclosed.)
evolve_agent:
  llm_config:
    reasoning:
      effort: "high"

# No web exploration (no SERPER key) and no notifications.
explore_agent:
  enabled: false
notify:
  enabled: false
"""
    OVERLAY_PATH.write_text(overlay)
    return OVERLAY_PATH


def cmd_prepare(args) -> None:
    tasks = build_dataset(DATASET_DIR)
    overlay = write_overlay(DATASET_DIR, args.iterations, args.n_concurrent, args.timeout_multiplier)
    print(f"dataset dir : {DATASET_DIR}  ({len(tasks)} tasks)")
    print(f"  tasks     : {tasks}")
    print(f"overlay     : {overlay}")
    print(f"iterations  : {args.iterations}  (gpt-5.4 actor=high, evolve=xhigh, ADB off, explore off)")
    print("\nrun the AHE arm with:")
    print(f"  cd {AHE} && uv run python evolve.py --config {overlay}")


def cmd_extract_best(args) -> None:
    exp_dir = Path(args.exp_dir)
    out_dir = Path(args.out_dir)
    best_json = exp_dir / "best_ever.json"
    workspace = exp_dir / "workspace"
    if not workspace.exists():
        raise SystemExit(f"no workspace at {workspace}")
    best_iter = None
    if best_json.exists():
        best_iter = json.loads(best_json.read_text()).get("iteration")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(workspace, out_dir)
    if best_iter is not None:
        tag = f"iteration_{best_iter}"
        r = subprocess.run(["git", "-C", str(out_dir), "checkout", tag, "--", "."],
                           capture_output=True, text=True)
        if r.returncode != 0:  # fall back to the final committed state
            print(f"[warn] could not checkout {tag}: {r.stderr.strip()}; using final workspace")
        else:
            print(f"checked out AHE best iteration {best_iter} ({tag})")
    print(f"AHE best harness -> {out_dir}")
    print(f"score it with: python examples/tb2_score.py {out_dir} --label ahe --out /tmp/tb2_ahe.json")


def main() -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("prepare")
    p.add_argument("--iterations", type=int, default=5)
    p.add_argument("--n-concurrent", type=int, default=4)
    p.add_argument("--timeout-multiplier", type=float, default=3.0)
    p.set_defaults(func=cmd_prepare)
    e = sub.add_parser("extract-best")
    e.add_argument("exp_dir")
    e.add_argument("out_dir")
    e.set_defaults(func=cmd_extract_best)
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
